service: serverless-demo
provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: us-west-2
  memorySize: 128
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
          
plugins:
  - serverless-offline
